---
- id: psscriptanalyzer
  name: PSScriptAnalyzer
  description: Lint PowerShell files with PSScriptAnalyzer
  entry: psscriptanalyzer-hook
  language: python
  files: \.(ps1|psm1|psd1)$
  minimum_pre_commit_version: "2.9.0"
  additional_dependencies: []
  args: []

- id: psscriptanalyzer-format
  name: PSScriptAnalyzer Formatter
  description: Format PowerShell files with PSScriptAnalyzer
  entry: psscriptanalyzer-hook
  language: python
  files: \.(ps1|psm1|psd1)$
  minimum_pre_commit_version: "2.9.0"
  additional_dependencies: []
  args: ["--format"]
