name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync --dev

    - name: Install PowerShell
      shell: bash
      run: |
        wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell
 
    - name: Build package
      run: uv build

    - name: Check package
      run: uv run twine check dist/*

    - name: Run ruff check
      run: uv run ruff check .
    
    - name: Run ruff format check
      run: uv run ruff format --check .
    
    - name: Run tests
      run: uv run pytest
    
    - name: Run mypy
      run: uv run mypy psscriptanalyzer_hook.py
    
    - name: Install package locally for pre-commit
      run: uv pip install -e .
    
    - name: Run pre-commit hooks
      run: uv run pre-commit run --all-files
